//
//  WirelessAddress.swift
//  ADBMonitor
//
//  Copyright © 2026 Mories Deo Hutapea,S.E.,S.Kom
//

import Foundation

/// Validation of user input for ADB connections over Wi-Fi.
enum WirelessAddress {

    static let defaultPort = 5555

    /// Turns user input into `host:port`, or `nil` if it is not valid.
    ///
    /// - Parameter requirePort: `true` for pairing, which has no default port.
    /// The host may only contain letters, digits, dots, and hyphens (IPv4 or hostname); IPv6 is not supported.
    static func normalized(_ input: String, requirePort: Bool = false) -> String? {
        let trimmed = input.trimmed
        guard !trimmed.isEmpty else { return nil }

        let parts = trimmed.split(separator: ":", omittingEmptySubsequences: false).map(String.init)
        guard parts.count <= 2, let host = parts.first, isValidHost(host) else { return nil }

        if parts.count == 2 {
            guard let port = Int(parts[1]), (1...65535).contains(port) else { return nil }
            return "\(host):\(port)"
        }
        return requirePort ? nil : "\(host):\(defaultPort)"
    }

    /// ADB pairing codes are always 6 digits.
    static func isValidPairingCode(_ code: String) -> Bool {
        let trimmed = code.trimmed
        return trimmed.count == 6 && trimmed.allSatisfy { $0.isASCII && $0.isNumber }
    }

    /// A QR pairing password is generated by the app: ASCII letters and digits only, safe as an `adb` argument.
    static func isValidQRPassword(_ password: String) -> Bool {
        !password.isEmpty && password.count <= 64 && password.allSatisfy { $0.isASCII && ($0.isLetter || $0.isNumber) }
    }

    private static func isValidHost(_ host: String) -> Bool {
        guard !host.isEmpty, !host.hasPrefix("-"), !host.hasPrefix(".") else { return false }
        return host.allSatisfy { $0.isASCII && ($0.isLetter || $0.isNumber || $0 == "." || $0 == "-") }
    }
}
